functionsDirectory = "/tmp/Noobru-Address-Verifier-project2/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "/tmp/Noobru-Address-Verifier-project2/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/tmp/Noobru-Address-Verifier-project2/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"